name: Deploy Vartalap

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy on VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: vartalap.in.net
          username: root
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo "Starting deployment..."

            cd ~/vart/VARTALAP

            echo "Pulling latest code"
            git pull origin main

            echo "Installing dependencies"
            npm install

            echo "Building frontend"
            npm run build

            echo "Restarting backend"
            pm2 restart vartalap-backend

            echo "Restarting frontend"
            pm2 restart vartalap-frontend

            echo "Deployment completed"